export const SET_ACCESS_TOKEN = 'SET_ACCESS_TOKEN';
export const SET_REFRESH_TOKEN = 'SET_REFRESH_TOKEN';
export const DELETE_ACCESS_TOKEN = 'DELETE_ACCESS_TOKEN';
export const DELETE_REFRESH_TOKEN = 'DELETE_REFRESH_TOKEN';
export const SET_MEMBER_ID = 'SET_MEMBER_ID';
export const DELETE_MEMBER_ID = 'DELETE_MEMBER_ID';
export const SET_BIRTH = 'SET_BIRTH';
export const DELETE_BIRTH = 'DELETE_BIRTH';
export const SET_HEART = 'SET_HEART';
export const DELETE_HEART = 'DELETE_HEART';
export const SET_SEX = 'SET_SEX';
export const DELETE_SEX = 'DELETE_SEX';
export const SET_ACCESS_TOKEN_EXPIRES_AT = 'SET_ACCESS_TOKEN_EXPIRES_AT';
export const SET_REFRESH_TOKEN_EXPIRES_AT = 'SET_REFRESH_TOKEN_EXPIRES_AT';
export const DELETE_ACCESS_TOKEN_EXPIRES_AT = 'DELETE_ACCESS_TOKEN_EXPIRES_AT';
export const DELETE_REFRESH_TOKEN_EXPIRES_AT =
  'DELETE_REFRESH_TOKEN_EXPIRES_AT';
